### ISSUE TITLE
lusca with client-sesson fails

### ISSUE THREAD

**Issue by dearsmk** [krakenjs/lusca#65]
I was trying to use lusca with client-session library and it fails with the below error. Can you please share your views.

lusca requires req.session to be available in order to maintain state

Error: lusca requires req.session to be available in order to maintain state
    at Object.create (/Users/msubbiah/sample/sessionapp/node_modules/lusca/lib/token.js:13:15)
    at getCsrf (/Users/msubbiah/sample/sessionapp/node_modules/lusca/lib/csrf.js:34:22)
    at checkCsrf (/Users/msubbiah/sample/sessionapp/node_modules/lusca/lib/csrf.js:57:20)
    at Layer.handle [as handle_request] (/Users/msubbiah/sample/sessionapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/msubbiah/sample/sessionapp/node_modules/express/lib/router/index.js:312:13)
    at /Users/msubbiah/sample/sessionapp/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/msubbiah/sample/sessionapp/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/msubbiah/sample/sessionapp/node_modules/express/lib/router/index.js:271:10)
    at clientSession (/Users/msubbiah/sample/sessionapp/node_modules/client-sessions/lib/client-sessions.js:630:5)
    at Layer.handle [as handle_request] (/Users/msubbiah/sample/sessionapp/node_modules/express/lib/router/layer.js:95:5)

**Comment by jasisk** [comment]
Precisely as it reads. `req.session` needs to be available. In other words (as mentioned in the [README](https://github.com/krakenjs/lusca/blob/6c9a4663a58448497acd7e4aee7f35ae2f47e55d/README.md)):
> **Please note that you must use [express-session](https://github.com/expressjs/session), [cookie-session](https://github.com/expressjs/cookie-session), their express 3.x alternatives, or other session object management in order to use lusca.**

So add a session provider ([express-session](https://github.com/expressjs/session) is totally sufficient for development though not for production) before lusca and all should be good.

**Comment by jasisk** [comment]
Note that if you're using lusca by means of [kraken](https://github.com/krakenjs/kraken-js), both [a session provider and lusca are preconfigured](https://github.com/krakenjs/kraken-js/blob/64f764160ee8491141960fc7755fdf05e7ae6776/config/config.json#L95-L131) so no need to add either, merely provide overrides as necessary.

**Comment by jasisk** [comment]
Ack. Just read up on [client-session](https://github.com/mozilla/node-client-sessions). Strangely, they're not following the convention of making the session object available on `req.session` by default.

Try setting the `cookieName` property in the config object you set for client-session to `session`. E.g.:
``` js
app.use(clientSession({ cookieName: 'session' }));
```
